<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cfg</string>
		<string>conf</string>
		<string>config</string>
		<string>ini</string>
		<string>prop</string>
	</array>
	<key>name</key>
	<string>Generic Config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Color (with alpha): #aacc4322, #bf34fa, #ccc</string>
			<key>match</key>
			<string>#([a-fA-F0-9]{8}|[a-fA-F0-9]{6}|[a-fA-F0-9]{3})\b</string>
			<key>name</key>
			<string>constant.other.genconfig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.genconfig</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-dash.genconfig</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.genconfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>One line comment</string>
			<key>match</key>
			<string>(?:(?:^\s*)|\s+)(?:(#.*)|(--\s+.*)|([^:]//.*))$
?</string>
			<key>name</key>
			<string>meta.comment.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>; one line comment</string>
			<key>match</key>
			<string>(?:(?:^\s*)|\s+);\s*(?=.).*$
?</string>
			<key>name</key>
			<string>comment.line.number-sign.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Number or number with unit (like 10k, 12M, 92dpi etc) and also hex like values 0xdf</string>
			<key>match</key>
			<string>\b[0-9]+([a-zA-Z]+)?\b</string>
			<key>name</key>
			<string>constant.numeric.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constant</string>
			<key>match</key>
			<string>\b([tT]rue|[fF]alse|TRUE|FALSE)\b</string>
			<key>name</key>
			<string>constant.language.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constant</string>
			<key>match</key>
			<string>\b(?&lt;!-)([oO]n|[oO]ff|ON|OFF|[yY]es|[nN]o|YES|NO|[nN]ull|NULL|[nN]one|NONE|nan|NaN|NAN)(?!-)\b</string>
			<key>name</key>
			<string>constant.language.genconfig</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#double_string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#single_string</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>One line word, or word with following {, or [word] or &lt;word&gt;</string>
			<key>match</key>
			<string>(?:^\s*(\w+)\s*(?={))|(?:^\s*(\w+)\s*$)|(^\s*\[.*\]\s*$)|(^\s*\&lt;.*\&gt;\s*$)</string>
			<key>name</key>
			<string>storage.type.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>(^\s*|\b)(?&lt;![.-])(function|define|ifn?def|endif|macro|insertmacro|index|location|alias|include|rewrite|if|then|else|start|stop|restart|with|alert|internal)(?![.-])\b</string>
			<key>name</key>
			<string>keyword.other.genconfig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.genconfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Colorize key in lines like: key = value or key: value or key value</string>
			<key>match</key>
			<string>^\s*(\w[\w-]*)[\s=:]\s*</string>
			<key>name</key>
			<string>meta.param.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Var name: %name, %name%, $name, $name$, ${name}, %{name}, %(name), $(name)</string>
			<key>match</key>
			<string>([\%\$@]{1,2}\{\w+\}[\%\$@]{0,2})|([\%\$@]{1,2}\(\w+\)[\%\$@]{0,2})|([\%\$@]{1,2}\w+[\%\$@]{0,2})</string>
			<key>name</key>
			<string>storage.source.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constant like names (ie in uppercase: NAME, SOME_NAME)</string>
			<key>match</key>
			<string>\b[A-Z_][A-Z_0-9]*\b</string>
			<key>name</key>
			<string>support.constant.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>URL like strings (http://name.org, ssh://111.22.33.4:42)</string>
			<key>match</key>
			<string>\b(?:(\w+://.*)|localhost)\b</string>
			<key>name</key>
			<string>constant.other.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>RegExp</string>
			<key>match</key>
			<string>\^.*\$</string>
			<key>name</key>
			<string>string.regexp.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>(!|\~|%|=|\^|\+|\-|\&lt;|\&gt;|\?|/|\*|\|)</string>
			<key>name</key>
			<string>keyword.operator.genconfig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Mime types (text/plain, application/x-javascript etc)</string>
			<key>match</key>
			<string>\b(?&lt;!/)[\w\-\.\+]+/[\w\-\.\+]+(?!/)\b</string>
			<key>name</key>
			<string>support.type.genconfig</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.genconfig</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>function call: name()</string>
			<key>match</key>
			<string>\b(\w+)\b\(</string>
			<key>name</key>
			<string>meta.function.genconfig</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>double_string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.genconfig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\s*"</string>
					<key>name</key>
					<string>constant.character.genconfig</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#double_string</string>
				</dict>
			</array>
		</dict>
		<key>single_string</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.signle.genconfig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\s*'</string>
					<key>name</key>
					<string>constant.character.genconfig</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single_string</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.genconfig</string>
	<key>uuid</key>
	<string>6c0abe56-18d2-4957-ac45-01fa1a0cb62a</string>
</dict>
</plist>
